# Generated by Django 3.2.23 on 2023-11-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greating',
            old_name='request',
            new_name='greate',
        ),
        migrations.RemoveField(
            model_name='greating',
            name='response',
        ),
    ]
